# Generated by Django 5.1.3 on 2025-08-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipe", "__first__"),
        ("projetotag", "__first__"),
        ("tag", "__first__"),
        ("usuario", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("introducao", models.TextField()),
                ("resumo", models.TextField()),
                ("referencial_teorico", models.TextField()),
                ("desenvolvimento", models.TextField()),
                ("resultados", models.TextField()),
                ("conclusao", models.TextField()),
                ("referencias", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos_autorados",
                        to="usuario.usuario",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipe_projeto",
                        to="equipe.equipe",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projetos",
                        through="projetotag.ProjetoTag",
                        to="tag.tag",
                    ),
                ),
            ],
        ),
    ]
