# Generated by Django 5.1.3 on 2025-08-20 01:10

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("datanasc", models.DateField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Aluno", "Aluno"),
                            ("Orientador", "Orientador"),
                            ("Avaliador", "Avaliador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("add_em", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
